import axios from "axios";

export const emptyData: IData = {
  url: "",
  repository_url: "",
  labels_url: "",
  comments_url: "",
  events_url: "",
  html_url: "",
  id: 0,
  node_id: "",
  number: 0,
  title: "",
  user: {
    login: "",
    id: 0,
    node_id: "",
    avatar_url: "",
    gravatar_id: "",
    url: "",
    html_url: "",
    followers_url: "",
    following_url: "",
    gists_url: "",
    starred_url: "",
    subscriptions_url: "",
    organizations_url: "",
    repos_url: "",
    events_url: "",
    received_events_url: "",
    type: "",
    site_admin: false,
  },
  state: "",
  locked: false,
  assignee: null,
  assignees: [],
  milestone: {
    url: "",
    html_url: "",
    labels_url: "",
    id: 0,
    node_id: "",
    number: -1,
    title: "",
    description: "",
    creator: {
      login: "",
      id: 0,
      node_id: "",
      avatar_url: "",
      gravatar_id: "",
      url: "",
      html_url: "",
      followers_url: "",
      following_url: "",
      gists_url: "",
      starred_url: "",
      subscriptions_url: "",
      organizations_url: "",
      repos_url: "",
      events_url: "",
      received_events_url: "",
      type: "",
      site_admin: false,
    },
    open_issues: 0,
    closed_issues: 0,
    state: "",
    created_at: "",
    updated_at: "",
    due_on: null,
    closed_at: null,
  },
  comments: 0,
  created_at: "",
  updated_at: "",
  closed_at: null,
  author_association: "",
  active_lock_reason: null,
  body: "",
  timeline_url: "",
  performed_via_github_app: null,
  state_reason: null,
  reactions: {
    url: "",
    total_count: 0,
    "+1": 0,
    "-1": 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  },
  labels: [],
};

export function formatDate(date: string) {
  const dateObject = new Date(date);

  const formattedDate = dateObject.toLocaleDateString("ko-KR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return formattedDate;
}

export const axiosInstance = axios.create({
  baseURL: "https://api.github.com",
  headers: {
    Authorization: `Bearer ${process.env.REACT_APP_GITHUB_ACCESS_TOKEN}`,
  },
});
